### PR TITLE
Add short code to cli so I can find server record

### PR DESCRIPTION
**Pull request by potofpie**
Not sure how to make local dev easy here? 🤔

### CODE REVIEW

**Comment by jhaynie** [comment]
we should add a new enroll command that takes this code as the only argument

**Comment by potofpie** [comment]
> we should add a new enroll command that takes this code as the only argument

Are we thinking this will just write the api key to a file then start the server or just load in and start?

**Comment by robindiddams** [comment]
> > we should add a new enroll command that takes this code as the only argument
> 
> Are we thinking this will just write the api key to a file then start the server or just load in and start?

write to a file and have server check for it when it starts up. In future we'll have enroll setup a windows service, unix daemon that runs in the background and gets to work

**Comment by potofpie** [comment]
We went a different route

**Pull request closed without merging**
